import random
print('Генерация целого числа')
start = int(input('Начало границы: '))
stop = int(input('Конец границы: '))
print(f'\tСлучайное целое число: {random.randint(start, stop)}')
print()
print('Генерация вещественного числа')
start = float(input('Начало границы: '))
stop = float(input('Конец границы: '))
print(f'\tСлучайное вещественное число: {random.uniform(start, stop):.1f}')
print()
print('Генерация случайного символа')
start = ord(input('Начало границы: '))
stop = ord(input('Конец границы: '))
print(f'\tСлучайный символ: {chr(random.randint(start, stop))}')
